name: ci-stable-release

on:
  push:
    branches: [main]
    paths:
      - "STABLE-RELEASE"
    #  - ".github/workflows/ci-stable-release.yml"

jobs:
  push-stable-version:
    name: Create KubeArmor stable release
    if: github.repository == 'kubearmor/kubearmor'
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Install regctl
        run: |
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
          chmod 755 regctl
          mv regctl /usr/local/bin

      - name: Check install
        run: regctl version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Generate the stable version of KubeArmor in Docker Hub
        run: |
          STABLE_VERSION=`cat STABLE-RELEASE`
          regctl image copy kubearmor/kubearmor:$STABLE_VERSION kubearmor/kubearmor:stable --digest-tags

  update-helm-chart:
    name: Update KubeArmor Helm chart version
    if: github.repository == 'kubearmor/kubearmor'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Update Chart.yaml
        id: update
        run: |
          echo "STABLE_VERSION=`cat STABLE-RELEASE`" >> $GITHUB_OUTPUT
          sed -i -e "s/appVersion:.*/appVersion: ${{ steps.update.outputs.STABLE_VERSION }}/g" deployments/helm/Chart.yaml
          sed -i -e "s/version:.*/version: ${{ steps.update.outputs.STABLE_VERSION }}/g" deployments/helm/Chart.yaml

      - name: Create PR to update chart version on kubearmor/main
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-helm-${{ steps.update.outputs.STABLE_VERSION }}
          add-paths: "deployments/helm/Chart.yaml"
          commit-message: "[Automated] Update Helm Chart To ${{ steps.update.outputs.STABLE_VERSION }}"
          title: "[Automated] Update Helm Chart To ${{ steps.update.outputs.STABLE_VERSION }}"
          base: main
          signoff: true
          delete-branch: true

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          # Access token which can push to a different repo in the same org
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          charts_dir: deployments
          # repo where charts would be published
          owner: kubearmor
          repository: charts
          branch: gh-pages
          charts_url: https://kubearmor.github.io/charts
